name: Update and Build Docker Image

on:
  workflow_dispatch:
    inputs:
      hydrus_tag:
        description: 'Tag version to update the hydrus to'
        required: true
        type: string
jobs:
  build-dockeimage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v5
        
      - name: Run a script
        run: ./update.sh ${{ github.event.inputs.hydrus_tag }}
      - name: Release
        uses: softprops/action-gh-release@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}
          
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/hydrus-server-docker:${{ github.event.inputs.hydrus_tag }}
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/hydrus-server-docker:${{ github.event.inputs.hydrus_tag }}
